### ISSUE TITLE
Array without quotes in attribute value

### ISSUE THREAD

**Issue by martinhschei** [rudiedirkx/graphql-query#10]
First, i have solved this in my php code, but i might have missed how this package handles this, but for me it seems like it doesn't.

i need to provide this value:

    modes:[foot]

but if i do this:

    $this->trip->attribute('modes', ['foot'])

it comes with the qutoes after the query is built and the api call fails with validation error on that value, because the API expect the value inside the array to be without quotes.

I have looked around in the code for this project and found this (which put me on track to solve the case for me):

```
protected function renderAttributeValue($value) {
    // Enums are unquoted strings
	if ($value instanceof Attribute) {
		return (string) $value;
	}
```

But is there support in this package to just give it an array somehow and it figures out that the array values should be handled as enums?

EDIT:
if this repo is alive and does not support this, i will gladly make a pr with a fix.

**Comment by rudiedirkx** [comment]
I'm alive!

What does an array with unquoted values mean? Is that valid GraphQL? Are the values ENUMs? What is `foot`? It's not a variable, it's not a string, it must be an ENUM (usually UPPERCASED).

If it is an enum, do it like an enum:

    $query->trip->attribute('modes', [Query::enum('foot')]);

Output:

    trip (modes: [foot])

And you should really uppercase ENUMs, if you can, for clarity.

**Comment by rudiedirkx** [comment]
Oh, you said ENUM already. I can't read.

**Comment by martinhschei** [comment]
The values are strings in an array with 1 or more elements.

Your example is similar to how i solved it, but i also added support for multiple items.

But there is no function were an array can be interpreted directly as enums without the need to reference Enums:: directly?

Nice package, saved me time!

**Comment by rudiedirkx** [comment]
I meant _what_ they represent in GraphQL. Not _how_ they're represented in PHP. So, ENUMs =)

Maybe a single function that creates an array of enums? Something like:

    $query->trip->attribute('modes', Query::enums('foo', 'bar'));

If you have a better idea - I don't doubt it - PR me. Or give me an example right here, probably quicker.
